// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import dotenv from  "dotenv";
import { defineConfig } from "prisma/config";

const ENV = "dev";

if(ENV != "dev")
{
dotenv.config( {path: ".env.local"})
}else{
  dotenv.config( {path: ".env"})
}
console.log('foo')

// process.env.NODE_ENV !== "production" ? process.loadEnvFile('.env')  : process.loadEnvFile('.env.local') ;

console.log(process.env["DATABASE_URL"])
console.log(process.env.NODE_ENV)

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: `tsx prisma/seed.ts`,
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
